{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-genalg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/genalg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/genalg/genalg_{{ version }}.tar.gz
  sha256: caee6c5f3c04176c39f03037d2ee164eebac0429f9a522460eedfe8274f898f8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('genalg')"           # [not win]
    - "\"%R%\" -e \"library('genalg')\""  # [win]

about:
  home: https://github.com/egonw/genalg
  license: GPL-2.0-only
  summary: R based genetic algorithm for binary and floating point chromosomes.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - FrodePedersen
    - ArneKr
    - MathiasHaudgaard

# Package: genalg
# Version: 0.2.0
# Date: 2015-03-15
# Title: R Based Genetic Algorithm
# Author: Egon Willighagen and Michel Ballings
# Maintainer: Michel Ballings <Michel.Ballings@gmail.com>
# Description: R based genetic algorithm for binary and floating point chromosomes.
# URL: https://github.com/egonw/genalg
# BugReports: https://github.com/egonw/genalg/issues
# License: GPL-2
# Packaged: 2015-03-16 07:33:19 UTC; michelballings
# Repository: CRAN
# Date/Publication: 2015-03-16 08:45:54
# NeedsCompilation: no
