travis:
  secure:
    BINSTAR_TOKEN: tFwSlAAl8Ftp/v1+A4uOYez5+T9GkOuXrsHn3s58q9YxOhvd+zqcmeLSe9D/S1tXpcmTMGJVl6klca8XCjoktWoTLGPwIozCkww/s4dV2iNZnVJDwbrwt3KD9XzJz02K6TMYdn58Zi0TpA/QMpMlcsDc0lIeiKif5F2LdKToCHqKsRAdtzMOCHasjruU69LRI1tsWEJxvPQ5ck24DKOSvCTBXSlNl/6RWHOVpw7KQteQMQ3Zhaa+hBI4ju9Igf8mrO11I+TawZ+n4TUGfmoQ/ifRcSIwk7AG7AGKOSe86V7vnKgqBLeUXlMSkrSORDNslX2wOuZyDmulRC/ohbBTzqbdZe9hT08fmJpRS53fzzXuagHPHmvu03YiXa+K3fVPN3RCAcsFxqjsIe9MjlKvunz6TOl0bDotn5Rq0W4EOJbfj4MRcue4UjnZmZ9fbxe4RIA8RCOt5lhUeeYQt44ZUkxNOaZ73icANzwDZphD95fFZjZSfhDgqsHlxmUW2k4FYSsA9M7BDxfbXmTKpPBqqtT2iqUDYmrGjMCYQK3whJc5cy3XxDaRWXn9u0IImLJ009/UzweOWqaRPYUsv3s9M/WwomyUfTMJ9Ya4Q77ivP7WTutDX99WPX10gi6P00oXh+ZnFTi0qyn6b1XaLOucW+ekHHd1aoHC3bIo7XwcSVU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
