travis:
  secure:
    BINSTAR_TOKEN: qC2U0xrZY/RtPjVM/iKLZneFhbqlKUZWIPkWxEaUADkZoVeHxEzD62lYDKjcqbiOKhMS6qv+yKGScR6Swl7JleHNonEyrB4gtgXdkp0joTX9tZFHLYOD9dE1iDKq3InSj5paC/ESoiQZ3Oa+gCSxNvLxvKlVFqvWRAWRyn2mzyz3ekb4B+yu361k1Yg5MeaL07xIIyvaNslFUPS1Fkh118mHmc7+GdmjnWxwAzz0s5lBopzomJV0DmvvEjyYD+krv1+Tl/M2lBHKdJxCfrogcKZaqMhD5Y/W4EWsHNikVyxPTF/stkFapMcdRAATliHq7RYD2Llhrq887n/OODPXbdYaP1TxgCdwsNCJ8weZThQpYDbWhjcUt7Yu/nfY7d9vmE88HFg/yKgpoodqj5og8301iGjv3vpfnzWAn4VQ/scTw+G/iR3ulEwGjUOrq5b5JxrYxehEjC8x1XNPiNqtoORxA8xMeWL8xm8Znz4ubWYEwUGVM5bQbVA8uarCLi06aZ/VvN6bRrX1r4Sh1/JSVaUw103WMpATVUSa5jgXU4dm4h8pBVvPE4ksVbmB8lHWpVVcpjHxczNd9UCB/ImR9jhtWsq6DGC1LRVlD3cvJFiL1VheW8zo93ZxqBrIPuxuXDYxHOSemvQc3o7mzTb3HrjnFAjshXztExIl0wf/1G8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
