travis:
  secure:
    BINSTAR_TOKEN: YmRG8yYvKXbamDzQQzLd346uPTSjYzg8kLWVnBMYTi5J2j7DfHYd0bXwh9R4ThjMAYbMH0tAUGR9IO396F53rU7RZfXK7t1BcY3qYu7BuWMrv5vGqWTCu2fIVnM+E9/sOV+4x0fi1+a1PuxrPH39lT5q+pXZONJzxKcYXPsUI5WtPyZ3lod99dhpLlU6ri/vNENXbxQ8rH2nSWDdgdiAzgy06KoMhoio/wjOI9n8eL0gtF/zG+GpndWH2oPekeG/2WfUWrkipg6c6n1O+t0j+fENfmK8kjedZVDse7aaEv3ZyEbLD0f0v54ePPgzc7466nv+A3zqUZRBv/Om9S/U4Tb/VyJ7twYIA9+V2zwB0raj9G8dR3yR/tmhxXJ+LLggrwxdScSIV0/QDlVNS2y5XP0bu5pH4Grbv/qxqulCLoUrBQAfoqeXYxx+DeYD5i3VTIZgjR8dwua8/pUGklmpETV9BOOerEZ9AFa/C3Olrc7VtuMQo3cRFspAWf2WE6voMB9DAWpF6dAFOpVK4JF9tTzuf+Piysope3heVIWiQ1BVhIWF7C/CF71avHeO39kg1v9V6qgTnxUe5IVzivjOBNeP31w93fsTVULN7T4e1iG0DN4UWntpzzimIZsTNzoluet81weABbCEbGupr1WMZd1X3DW4hbf3CiWgGv7dEYQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
