travis:
  secure:
    BINSTAR_TOKEN: MZBHCCxQ5s8zmO/cm77tyuaNIEtLqeGTStEyDpLQVRe0J3nxJI6LFZ2aWjJ68Q5BgGGatgi30LdYA2ptEq/hRbB1tSn1uyc6VbOHXMSht00o2xJhQ8pXyYD++AggMOB3vF2qHA8t7AW6+jCy/VzfAIqazMWY5XKDKkSQqz3+jF/WnVEBlL/D6E5yKWUw9UTHZsIeaJvtPLzNoOdTtZLGp4K7dBzUBg96goAWLzN8ZHrbCdsMkveTlxUggOy8niL3G6k0IVQuyF0rKCVN/UwhFdemG1l0aKzMfzhdp1bBErX+CkA0HLZ/QF/VpYVbJLSC/L8t/jA2XVvk2GXQfjGEhHRIEzpHpfZHaaeT3LuMvZUHYorGF+DhAAbW487hM3Rp9zsMaO4vbbHBs3cpRtj0Q+EBTYPkf0IaAQhGK3kM3pFopphp2OFHhtqERByJHbmq5y1D/IWUeaGhv4ukHg3626GvB/ktHe0K5R19f9Sx+MTM9hcLH5Ju7yWID1eM3F0CQwI0CKYlJvQ5M9keWVn6a7qGXUebHlXh3E0wmMPYg7jaXENlAHu7FqazBOCOBbjjV87W1bzUMyzQhpaOhw2B+hmAZzwUfmludoyaESnvPPp4PZ8qsxDe0/B7Y852ag6iYvd+oJCCyjspHBHTBU4Utmb9fr6L2ALf4x9Qnhb7ztI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
