travis:
  secure:
    BINSTAR_TOKEN: dSmRyhZ5no6T4BZhKGNB7G9J4Dt4njMCXR/0hFGBJqdxkmvn6kgRNPTcVvvzWSGPrNplbKGdncyEdPpAOdnFZ4oWF8LNzp75lahTQdKE1Gj7kCg8g7JBAcluJtPxx0pQ1mKiIidqKunAhC5xB/o3iySzQ1oh2gjOVPjobf3yp3H9bGw53MwkAKhvlNlHjchgZwaC7iiu5ldIP3ZQNf1LyPo10lAOF+i4RYN/4VJ3k9bUQVF2KKZBjakFCnwk3dKU0vdzN6yzK5cs8USLIqZlfJTCA28mA89Xq2MkkauDZwJk60Lm6JRiGkF0vFfoTD5Zw7udHxHALj+ZGwSwjl6na0MpYskSpfPX6BXuxUSMx2IZXyrLtkNhMfjnGtUZYLOTor/lcXxELiPrH6VGVrl00u1f+dxcNXaHg2SUUtNAYvYo9xkOlbEygdhBiXkgvuDrPfN5uyeAOoIzer8RnPe8SWfavvdJ+rnRLm9M4VlIpbcpdlHpTYTB2XfM6MVH+WMUH1oc50BOZiuqK7YPGMXNE5SQh8EsvGgLxowYH5jMua5YLsWf/ZNhxHUXmwi6cehBi6Jq4RO8VyEac8mxIqDKa2Ucb6MPt11aSJUfLuoDGM1RCc9GhC5boertgQ23MZECdrmolauhg85wP9MOiis6aflxzuvsaVbc/ggI/Al1lqM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
